/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gameoflife

import kotlin.test.*


class AppTests {
    @Test
    fun `Can create a view`() {
        assertNotNull(GoLApplication())

    }
}
